cl Arrays.cpp /clr:safe
cl Boolean.cpp /clr:safe
cl BooleanLiteral.cpp /clr:safe
cl Boxing.cpp /clr:safe
cl CharLiteral.cpp /clr:safe
cl Chars.cpp /clr:safe
cl Decimal.cpp /clr:safe
cl Enums.cpp /clr:safe
cl FloatingPoint.cpp /clr:safe
cl Hello.cpp /clr:safe
cl IntegerLiteral.cpp /clr:safe
cl IntegerTypes.cpp /clr:safe
cl MainArgsNew.cpp /clr:safe
cl MainArgsTrad.cpp /clr:pure
cl ReferenceIndirect.cpp /clr:pure
cl StringFun.cpp /clr:safe
cl StringLiteral.cpp /clr:safe
cl ValueClass.cpp /clr:safe
